my_salesforce_source/force-app/main/default/objects/Loan_Application__c/Loan_Application__c.object-meta.xml
<CustomObject>
    <label>Loan Application</label>
    <nameField>
        <label>Loan Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

my_salesforce_source/force-app/main/default/objects/Loan_Application__c/fields/Currency_Code__c.field-meta.xml
<CustomField>
    <fullName>Currency_Code__c</fullName>
    <label>Currency Code</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ZAR</fullName>
            </value>
            <value>
                <fullName>USD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

my_salesforce_source/force-app/main/default/objects/Loan_Application__c/fields/Income__c.field-meta.xml
<CustomField>
    <fullName>Income__c</fullName>
    <label>Income</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

my_salesforce_source/force-app/main/default/objects/Loan_Application__c/fields/Normalized_Income__c.field-meta.xml
<CustomField>
    <fullName>Normalized_Income__c</fullName>
    <label>Normalized Income</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

my_salesforce_source/force-app/main/default/classes/LoanService.cls
public class LoanService {

    public Loan_Application__c submitLoan(Loan_Application__c loan) {


        Decimal rate = new ExchangeRateService(
            new HttpGetService()
        ).getRate(loan.Currency_Code__c, 'ZAR');

        loan.Normalized_Income__c = loan.Income__c * rate;

        insert loan;

        System.enqueueJob(
            new RiskQueueable(loan.Id, loan.Normalized_Income__c)
        );

        return loan;
    }
}