my_salesforce_source/force-app/main/default/objects/Loan_Application__c/Loan_Application__c.object-meta.xml
<CustomObject>
    <label>Loan Application</label>
    <nameField>
        <label>Loan Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

my_salesforce_source/force-app/main/default/objects/Risk_Assessment__c/Risk_Assessment__c.object-meta.xml
<CustomObject>
    <label>Risk Assessment</label>
    <nameField>
        <label>Risk Assessment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Risk Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

my_salesforce_source/force-app/main/default/objects/Risk_Assessment__c/fields/Calculated_At__c.field-meta.xml
<CustomField>
    <fullName>Calculated_At__c</fullName>
    <label>Calculated At</label>
    <type>DateTime</type>
</CustomField>

my_salesforce_source/force-app/main/default/objects/Risk_Assessment__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Loan Application</label>
    <referenceTo>Loan_Application__c</referenceTo>
    <relationshipLabel>Risk Assessments</relationshipLabel>
    <relationshipName>Risk_Assessments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

my_salesforce_source/force-app/main/default/classes/RiskQueueable.cls
public class RiskQueueable implements Queueable {

    private Id loanId;
    private Decimal income;

    public RiskQueueable(Id loanId, Decimal income) {
        this.loanId = loanId;
        this.income = income;
    }

    public void execute(QueueableContext context) {

        Integer retryCount = 0;
        Boolean success = false;
        Decimal score;

        while (retryCount < 3 && !success) {
            try {
                score = FakeRiskEngineService.calculateRisk(income);
                success = true;

            } catch (Exception e) {
                retryCount++;
                System.debug('Retry attempt: ' + retryCount);

                if (retryCount == 3) {
                    throw e;
                }
            }
        }

        Risk_Assessment__c risk = new Risk_Assessment__c();
        risk.Loan_Application__c = loanId;
        risk.Score__c = score;
        risk.Calculated_At__c = System.now();

        insert risk;
    }
}